Fix documentation to point out whether polygons/triangles should be clockwise/anticlockwise
zaidan/earclipper pull request #1
Opened 2018-09-21 00:34 UTC by timo-a

improves documentation by explicitly pointing out whether polygons/triangles should be clockwise/anticlockwise.

2018-09-21 01:27 UTC, zaidan requested changes
@timo-a thank you for your contribution. Pointing this out is a good idea and adding some examples is great. So I think we can merge this, but we need to fix the commit message first.
Typically you use some keyword like `Add`, `Change`, `Fix`, `Remove` or `Refactor` followed by a description what the commit does. Always present tense, because it describes what the commit does when you apply it. 
In this case I would suggest something like:
```git
Fix documentation to point out whether polygons/triangles should be clockwise/anticlockwise

* Add example to documentation for `toTriangle`
* Add example to documentation for `triangulate`
* Add example to documentation for `pointInTriangle`
* Add example to documentation for `isConvex`
```

You can use `git commit --amend` to change your commit message and `git push origin master --force` to update your feature branch.

2018-09-22 14:38 UTC, timo-a commented
I fixed the commit message!

2018-09-22 14:44 UTC, zaidan approved these changes
@timo-a thanks for your contribution

2018-09-22 14:44 UTC, merged

2018-09-22 14:53 UTC, zaidan commented
@timo-a to get listed as contributor, you have to add your commit email address to your Github account